import PDFDocument from "pdfkit";

class PDFService {
  generateRoadmapPDF(data: any) {
    return new Promise<Buffer>((resolve) => {
      const roadmap = data.roadmap;

      const doc = new PDFDocument({
        margin: 50,
      });

      const chunks: Buffer[] = [];

      doc.on("data", (chunk) =>
        chunks.push(chunk)
      );

      doc.on("end", () => {
        resolve(Buffer.concat(chunks));
      });

      doc
        .fontSize(24)
        .fillColor("#1e3a8a")
        .text(roadmap.title, {
          align: "center",
        });

      doc.moveDown();

      doc
        .fontSize(12)
        .fillColor("black")
        .text(
          `Target Role: ${data.targetRole}`
        )
        .text(
          `Study Time: ${roadmap.preferredStudyTime}`
        )
        .text(
          `Daily Hours: ${roadmap.dailyHours}`
        )
        .text(
          `Study Days/Week: ${roadmap.daysPerWeek}`
        );

      doc.moveDown();

      doc
        .fontSize(11)
        .fillColor("#374151")
        .text(
          `Generated from: ${data.generatedFrom}`
        );

      doc.moveDown(2);

      roadmap.days.forEach((day: any) => {
        doc
          .fontSize(16)
          .fillColor("#111827")
          .text(
            `Day ${day.day}: ${day.focus}`,
            {
              underline: true,
            }
          );

        doc.moveDown(0.5);

        doc
          .fontSize(11)
          .fillColor("#374151")
          .text(
            `Schedule: ${day.schedule}`
          )
          .text(
            `Study Hours: ${day.hours}`
          );

        doc.moveDown(0.5);

        day.tasks.forEach((task: string) => {
          doc.text(`• ${task}`, {
            indent: 20,
          });
        });

        doc.moveDown();
      });

      doc.moveDown(2);

      doc
        .fontSize(10)
        .fillColor("gray")
        .text(
          "Generated by SkillPilot AI - Your AI Powered Career Operating System",
          {
            align: "center",
          }
        );

      doc.end();
    });
  }
}

export default new PDFService();